name: Build with VCPKG

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually target the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: windows-latest, env: Windows x86_64, triplet: x64-windows-static }
          - { os: macos-latest, env: Mac Os x64, triplet: x64-osx }
          - { os: ubuntu-latest, env: Ubuntu x86_64, triplet: x64-linux }
    runs-on: ${{ matrix.os }} 
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4      
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - name: install vcpkg
        run : |
          git clone --depth 1  https://github.com/microsoft/vcpkg "$HOME/vcpkg"          
      - name: bootstrap vcpkg
        if: runner.os == 'Windows'
        run: |
          cd "$HOME/vcpkg"
          "bootstrap-vcpkg.bat"
      - name: bootstrap vcpkg
        if: runner.os != 'Windows'
        run: |
          cd "$HOME/vcpkg"
          "./bootstrap-vcpkg.sh"
      - name: Configure   
        run: |
          cp "$HOME/vcpkg/triplets/${{ matrix.triplet }}.cmake" "$HOME/vcpkg/triplets/community/${{ matrix.triplet }}-release-only.cmake"
          echo "set(VCPKG_BUILD_TYPE release)" >> "$HOME/vcpkg/triplets/community/${{ matrix.triplet }}-release-only.cmake"
          mkdir build
          cd build
          cmake "-DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}-release-only" "-DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake" ..
               
      - name: Build
        run: |
          cd build
          cmake --build . --config Release
      - name: Copy Binary And Assets
        run: |
          mkdir ./Release
          mkdir ./Release/ttftovircon
          cp build/Release/ttftovircon.exe ./Release/ttftovircon/
          cp ./README.md ./Release/ttftovircon/
          cp ./LICENSE ./Release/ttftovircon/
      - name: Store build
        uses: actions/upload-artifact@v4
        with:
          name: ttftovircon ${{ matrix.env }}
          path: ./Release/